version: "3.2"

services:

  git-deploy:
    build:
      context: .
    container_name: git-deploy
    volumes:
      - type: bind
        source: .
        target: /opt/app
    ports:
      - "4040:3000"
    restart: "always"
