version: "3.2"

services:

  git-deploy:
    build:
      context: .
    container_name: git-deploy
    environment:
      destination: "/srv/services/webserver"
      remote: "origin"
      branch: "stable"
      build_command: "docker-compose up --build -d"
    volumes:
      - type: bind
        source: "/srv/services/webserver"
        target: "/srv/services/webserver"
    ports:
      - "4040:3000"
    restart: "always"
